### ISSUE TITLE
Wrong popper version in dependency for bootstrap 5, can't use tooltips

### ISSUE THREAD

**Issue by bradsb** [twbs/bootstrap-rubygem#209]
This gem uses popper v1.16.0, when trying to use the bootstrap 5 tooltips this causes:
`Uncaught TypeError: Popper.createPopper is not a function`

In the [bootstrap docs](https://getbootstrap.com/docs/5.0/components/tooltips/), it links to version 2.6.0 of popper js:
https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js

My Gemfile.lock currently:
```
bootstrap (5.0.0.beta1)
      autoprefixer-rails (>= 9.1.0)
      popper_js (>= 1.14.3, < 2)
      sassc-rails (>= 2.0.0)
```

**Comment by rlsutton1** [comment]
I also found this. You can see the problem when I try to force the version..

```
Bundler could not find compatible versions for gem "popper_js":
  In Gemfile:
    popper_js (~> 2.6)

    bootstrap (~> 5.0.0.beta1) was resolved to 5.0.0.beta1, which depends on
      popper_js (>= 1.14.3, < 2)

```

**Comment by jirihradil** [comment]
I have the same problem.

**Comment by glebm** [comment]
This is already fixed on master. You can point to the version from master for now to work around this.

**Comment by RailsCod3rFuture** [comment]
Uncaught TypeError: Popper.createPopper is not a function -- I just updated the gem and its still not working...how do you target the master for this repository, just so that I can make sure I'm hitting the correct endpoint?

**Comment by glebm** [comment]
v5.0.0.beta2 has been released
